[pytest]

addopts = -v -s --html=reports/report.html --self-contained-html
testpaths = HomeworksProject/tests
markers =
    smoke: quick checks for basic functionality
    regression: full regression suite
    ui: tests related to UI elements

    login: tests related to login page
    registration: tests related to registration page
    links: test related to Links page

